x = int(input("Enter your Number:"))
print("Original Number:",x)
print("Left aligned (width 10):" + "{:< 10d}".format(x))
print("Right aligned (width 10):" + "{:10d}".format(x))
print("Center aligned (width 10):" + "{:^10d}".format(x))